### ISSUE TITLE
vscode-python causing silent dmypy failure

### ISSUE THREAD

**Issue by connorads** [microsoft/vscode-mypy#105]
# Problem

No mypy type hints 😢 

# Cause

Seems like the [default settings for vscode-python is setting `python.linting.mypyArgs` with an arg of `--follow-imports=silent`](https://github.com/microsoft/vscode-python/blob/8e0e59be81eae58c8120af5453ba178e3aa40aec/package.json#L843-L848) which is not supported by `dmypy` (https://github.com/python/mypy/issues/9475)

# Workaround

Set `"python.linting.mypyArgs": [],` in user or workspace `settings.json`

# Potential fix

Would a fix be to just [stop reading the legacy args here](https://github.com/microsoft/vscode-mypy/blob/179721a6806f1ff2181de4f6d59e207248e5f537/src/common/settings.ts#L63)?
Happy to try a PR if so 😉 

My reasoning: Given these legacy args are being deprecated in favour of plugins like this one? And that maybe the change to `dmypy` (https://github.com/microsoft/vscode-mypy/issues/53) now warrants this?

I'm fairly new to the Python world so I hope this makes some sense 😅 

# Demo

In `defaultSettings.json` we can see `python.linting.mypyArgs` with an arg of `--follow-imports=silent` 

![image](https://github.com/microsoft/vscode-mypy/assets/10026538/58c65d07-a5cc-4f34-abbb-8de46ca9104f)

We can see that `vscode-mypy` now reads this setting

![image](https://github.com/microsoft/vscode-mypy/assets/10026538/ae4a9d17-951b-4cbe-a352-00437b9c0517)

And when it passes the arg to `dmypy` we get a message to say it's not supported, and we do not get `Daemon started` 

![image](https://github.com/microsoft/vscode-mypy/assets/10026538/e61efd3f-79b4-40ba-a3ff-8c40c5fcc547)

After using the workaround we can see `Daemon started` and a type error in the console

![image](https://github.com/microsoft/vscode-mypy/assets/10026538/d1b6b1d9-2814-45a1-ab13-9d7489bfe282)

and in the editor

![image](https://github.com/microsoft/vscode-mypy/assets/10026538/515325c4-d2f2-478a-823a-2216aa2002aa)

**Comment by karthiknadig** [comment]
> Would a fix be to just [stop reading the legacy args here](https://github.com/microsoft/vscode-mypy/blob/179721a6806f1ff2181de4f6d59e207248e5f537/src/common/settings.ts#L63)?

Yes. And we are open for PRs on this.

**Comment by connorads** [comment]
Hey @karthiknadig, I've opened #107

**Comment by posita** [comment]
I don't think merely not reading the legacy args is the solution here. I'm _**still**_ encountering this, and I don't have that setting.

(Ref: python/mypy#9475 for visibility.)
