### ISSUE TITLE
mypy: error: unrecognized arguments: --new-type-inference

### ISSUE THREAD

**Issue by alexchandel** [microsoft/vscode-mypy#109]
The version of mypy shipped with this extension doesn't seem to take the `--new-type-inference` that's required for better type resolution.

**Comment by karthiknadig** [comment]
This is the version that is shipped: https://github.com/microsoft/vscode-mypy/blob/bd4e6062d1dc8bd0733ba801573e4c2755db09fc/requirements.txt#L31

Can you provide the version that supports the flag?
