### ISSUE TITLE
Option for using mypy instead of dmypy (daemon)

### ISSUE THREAD

**Issue by cpnielsen** [microsoft/vscode-mypy#115]
## Suggestion

Currently, a number of features are [buggy or unsupported](https://github.com/python/mypy/issues?q=is%3Aissue+is%3Aopen+dmypy) when using `dmypy` instead of calling the `mypy` command directly.

I am aware you can sort-of achieve this by setting the `mypy-typer-checker.path` to `mypy`, but it would be nice to be able to use the same mechanisms for using the chosen interpreter and and discovered mypy version (via "fromEnvironment" / "useBundled"), as seen here: https://github.com/microsoft/vscode-mypy/blob/main/bundled/tool/lsp_server.py#L557-L561

I imagine a setting like `useDaemon` which defaults to true. If set to false, and `path` not set, it would run the same logic as for the daemon, but calling the mypy module instead.

**Comment by karthiknadig** [comment]
I think this would be a useful setting.

FYI: `"mypy-typer-checker.path": [ "<python-path>", "-m", "mypy"]` will use `mypy` from environment or use bundled based on the  "fromEnvironment" / "useBundled"

**Comment by cpnielsen** [comment]
@karthiknadig I actually tried that, but `python` refers to the system path, as `subprocess.run` does not inherit the PATH of the language server. The only working setting was to use `./.venv/bin/mypy` (where `.venv` is the name of my virtualenv folder).

`fromEnvironment` works as expected with the non-path based approach, as the first argument there is `sys.executable`.

I can make a PR for this setting if you are open to it. I also noticed that if `mypy` returns nothing for a file that had an error before, the existing errors are not cleared out. Would you prefer that fix separate from this feature PR?

**Comment by karthiknadig** [comment]
@cpnielsen We are open for a PR on this.

> I also noticed that if mypy returns nothing for a file that had an error before, the existing errors are not cleared out. Would you prefer that fix separate from this feature PR?

A separate bug and PR would be best for this case.
