### ISSUE TITLE
Mypy not showing errors on newly created files 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-mypy#116]
This is when "mypy-type-checker.reportingScope" is set to "workspace"

If you create new files with errors reported  by mypy, it won't report their errors until you restart the server. 

Repro steps:
- Create new files with problems mypy should report
- Notice they are not reported as problems 

https://github.com/microsoft/vscode-mypy/assets/45497113/667bf272-728f-4138-8815-8e325ed0e424

**Comment by karthiknadig** [comment]
This is same as https://github.com/microsoft/vscode-mypy/issues/88
