### ISSUE TITLE
Document Default Interpreter

### ISSUE THREAD

**Issue by Kurt-von-Laven** [microsoft/vscode-mypy#144]
The `mypy-type-checker.interpreter` setting is helpfully documented in the README:

> Path to a python interpreter to use to run the linter server.

The default value is `[]`, but it isn't immediately clear what interpreter is used in this case. For instance, is `python.defaultInterpreterPath` used, or does the mypy extension ship with a Python interpreter?

**Comment by karthiknadig** [comment]
The python is the one selected in the python extension. We use an API from python extension to get the path to it.

We will update the text.
