### ISSUE TITLE
Capitalize instances of "python" in user-facing text 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-mypy#153]
Whenever there are user facing references like in settings, commands or descriptions, we should capitalize "Python".

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!

**Comment by Jyothirmaikottu** [comment]
Hi Luciana, I would like to work on this issue!

**Comment by karthiknadig** [comment]
@Jyothirmaikottu You can look at the following files where `python` is used and are user facing texts:
https://github.com/microsoft/vscode-mypy/blob/main/package.nls.json
https://github.com/microsoft/vscode-mypy/blob/main/package.json
https://github.com/microsoft/vscode-mypy/blob/main/README.md

**Comment by luabud** [comment]
https://github.com/microsoft/vscode-mypy/pull/159 and https://github.com/microsoft/vscode-mypy/pull/161
