### ISSUE TITLE
Have the possibility of full workspace scanning instead of per-file

### ISSUE THREAD

**Issue by basvandriel** [microsoft/vscode-mypy#164]
As the [mypy documentation](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-exclude) mentions in the third paragraph (see below quote), it's expected behavior to still have type checking when pointing to a file or module.

> Note that this flag only affects recursive directory tree discovery, that is, when mypy is discovering files within a directory tree or submodules of a package to check. If you pass a file or module explicitly it will still be checked. For instance, mypy --exclude '/setup.py$' but_still_check/setup.py.

It would be a nice feature to have a `mypy-type-checker.workspaceScanning` option, to scan the targeted workspace.

**Comment by karthiknadig** [comment]
@basvandriel This feature is already in pre-release. Please try it out. The setting is `mypy-type-checker.reportingScope` set it to workspace.
