### ISSUE TITLE
Unable to provide MYPYPATH environment variable

### ISSUE THREAD

**Issue by mayrholu** [microsoft/vscode-mypy#207]
Is there a way to set MYPYPATH somewhere? I need it to provide additional stubs. It seems that the .env File is ignored (#154). It worked with the old mypy-setup inside the Python-extension.

**Comment by karthiknadig** [comment]
@mayrholu you can use `python.analysis.extraPaths` as a workaround until #154 is addressed. We plan on addressing #154 soon.

Closing this here as this will be resolved by, #154
