### ISSUE TITLE
Only the first opened file gets linted when run as daemon

### ISSUE THREAD

**Issue by Mutantpenguin** [microsoft/vscode-mypy#222]
When activating the daemon, only the first opened file gets linted. When switching to another file nothing happens.

![2023-11-14_12h26_40](https://github.com/microsoft/vscode-mypy/assets/9027507/e93a4a0e-4047-4bb0-89e8-b95b8c550d49)

There are no errors from the extension itself in the output tab of this extension. I can see that the linter gets called for the file I just switched to, but no linting errors are shown in the output either.

Making changes to a file and saving it doesn't make a difference.

Apart from all of that, linting with the daemon (if it works at all) seems slower than directly invoking mypy.

## Example Workspace
[vscode-mypy.zip](https://github.com/microsoft/vscode-mypy/files/13348227/vscode-mypy.zip)

## My System
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Mypy Type Checker: v2023.6.0

Python 3.10.11

**Comment by karthiknadig** [comment]
That is an issue with `dmypy`, https://github.com/python/mypy/issues/15677 . We added the `mypy-type-checker.preferDaemon` setting to allow users to turn of daemon mode as it seems to have too many issues currently.
