### ISSUE TITLE
Certain errors underline too much

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode-mypy#251]
For example, an error of "Missing return statement" underlines the entire function in squiggly red. This is very disruptive as it pops up while I'm typing in the docstring. Often I add a dummy return statement just to shut it up until I finish writing the code, which is just asking for a bug.

![image](https://github.com/microsoft/vscode-mypy/assets/26465923/59a9c247-b6c0-4d1d-956e-1da1dd6b3fd6)

I think only the function name should be underlined in red - or maybe the return typehint?

**Comment by karthiknadig** [comment]
@shaperilio What is the output from mypy? This range is provided by the mypy library. See output> Mypy Type Checker for the exact ranges reported by mypy.

**Comment by shaperilio** [comment]
I could not defend `mypy` for including a line/column range that includes an entire function, but one could argue that, it being a command-line program, it's simply telling you where to go look in your editor of choice.

I'm here in my editor of choice and there's red/blue/whatever all over the screen and it makes it hard to work. I think in general (as in including #252), one can argue that it's the responsibility of the visualizer to interpret the output of the program in a productive way.

I think having large code blocks in "alarm" mode is too distracting to work. (On the other extreme, I also sometimes miss red squigglies that are only one character wide.) So perhaps you should consider alternative forms of highlighting large swaths of code, and maybe also very short ones.

**Comment by karthiknadig** [comment]
@shaperilio I think this still falls on `mypy`. Each particular case is error specific. Depending on an error `mypy` may want the entire function to be reported vs pointing out a just the definition line, we don't know the intent. We don't want to have to re-analyze the AST again after getting a report from `mypy` for each specific error case. `mypy` added the end line and column to make it easier for editors to highlight. I would say that it would be on `mypy` pick the right end line and column.

**Comment by karthiknadig** [comment]
We discussed this with the team and decided that we don't want to re-interpret the ranges provided by `mypy`. We want to keep the extension minimal in what it does for maintainability given the number of extensions we own. In this particular scenario it is better for the ranges to be improved in `mypy` itself, as it has the full context of what that particular issue is.

**Comment by shaperilio** [comment]
As much as I understand how much effort you all are willing to put in, I think asking another project to change their output to make your visualization tolerable is not appropriate. That's like saying "I wish images weren't stored as bytes, it should just be stored as voltage vs. time we don't have to do any work to make them show up on our display".

**Comment by brettcannon** [comment]
> I think asking another project to change their output to make your visualization tolerable is not appropriate.

I agree that the initial wording in the message wasn't great, so I tweaked the message. But we still don't want to "interpret" mypy results and instead display what mypy tells us to mark up. If you disagree w/ what that causes to be marked, then that's an ask for mypy (which is what I think the intent of the initial message was), or you can fork this repo and tweak how it works to meet your needs better.
