### ISSUE TITLE
"Function is missing type annotation" error marks entire function instead of just marking the function signature line

### ISSUE THREAD

**Issue by avivz** [microsoft/vscode-mypy#262]
I use mypy in --strict mode which also reports when functions are missing type annotations as an error. The extension marks  (via red underline) the entire function as erroneous, while it would be easier to understand if only the function definition is marked. 

Looking at the logs I see that the end_line and end_character reported by mypy include the entire function scope, so solving this probably requires handling this specific error in a different way. 

example: 

![image](https://github.com/microsoft/vscode-mypy/assets/5065029/edbead19-6214-4b9c-974c-d65fc03f59ba)

![image](https://github.com/microsoft/vscode-mypy/assets/5065029/bf74f3ad-8225-4996-a7b5-f913c6c015da)

**Comment by karthiknadig** [comment]
We avoid re-interpreting responses for the ranges. Users might want to preserve the ranges as provided by `mypy`. Changing the range would mean that we will now have to provide a way to get the ranges as provided by `mypy` if users prefer that. This also means that we may have to provided configurability at rule level for each case. Additionally, if `mypy` makes changes to these ranges, then we will need to handle this on a per version basis. 

We want to leave this to `mypy` to decide how these ranges are managed for the various cases. So, this is an ask for `mypy`, to change the range here to the function definition.
