### ISSUE TITLE
Warning when loading extension

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode-mypy#315]
### Expected Behavior

Warning messages must not be required

### Actual Behavior
<!-- What actually happened? —>
2024-08-08 21:00:58.923 [warning] [mypy-type-checker]: Couldn't find message for key settings.cwd.description.
2024-08-08 21:00:58.923 [warning] [mypy-type-checker]: Couldn't find message for key settings.ignorePatterns.description.

## Reproduction Steps:
<!-- How can we reproduce the bug? Please be as detailed as possible so we can help with your bug faster! —>
Install inside devcontainer, and watch on the output / server

**Comment by karthiknadig** [comment]
Thanks for the bug report, but unfortunately, we need some more information from you in order to triage this issue appropriately. Please follow the bug template to create a new bug with all the critical details we need for diagnosis.

Please include logs and any screenshots that might help.
