### ISSUE TITLE
what does `mypy-type-checker.showNotifications` do?

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode-mypy#34]
is it supposed to show a notification here? because when i set it to `always`, i never see any notifications.

![image](https://user-images.githubusercontent.com/57028336/235430795-a0801ad4-7dde-4af2-8f71-d4a29f3bd029.png)

also, why is it only available as a user option and not a workspace option?

![image](https://user-images.githubusercontent.com/57028336/235430965-7870320e-6533-4ed4-89a9-e1cecd7fec35.png)

**Comment by karthiknadig** [comment]
This Setting it to error, will show a visible notification in the editor whenever there is an error while running mypy.

**Comment by DetachHead** [comment]
is this where that notification should be displaying? or am i looking in the wrong spot

![image](https://github.com/microsoft/vscode-mypy/assets/57028336/72efbedf-7398-4621-b8a7-3690c00484db)

**Comment by karthiknadig** [comment]
That is correct.
