### ISSUE TITLE
Allow excluding 3rd party code

### ISSUE THREAD

**Issue by samskiter** [microsoft/vscode-mypy#38]
I have a submodule checked out in my repository and mypy is peppering it in errors and I don't seem to be able to find a way to exclude it. Strangely, when I visit python files in my venv, they don't get any errors (even if they have the same issue present in the file), so there must be some exclusion applied for those kinds of files by the extension.

I've tried using mypy.ini but as VSCode invokes mypy on the file itself, I still receive errors from this extension.

I'd like mypy to treat the submodule like it treats files in the venv... what's the recommended approach here?

**Comment by karthiknadig** [comment]
@samskiter Can you try adding `mypy.ini` it to `mypy-type-checker.args`?

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
