### ISSUE TITLE
`mypy.args` does not work

### ISSUE THREAD

**Issue by ccostello97** [microsoft/vscode-mypy#39]
<img width="342" alt="Screenshot 2023-05-28 at 12 04 46 PM" src="https://github.com/microsoft/vscode-mypy/assets/25142353/4f7d1541-6460-41db-a31b-b6d6e23c7a21">

`mypy.args` is not recognized, despite its mention in the README. Upon further investigation, no `mypy` configurations are available.

**Comment by karthiknadig** [comment]
@ccostello97 Sorry for the error in the read me, it will be updated soon. It should be `mypy-type-checker.args`
