### ISSUE TITLE
Mypy only prints out `Restarting: configuration changed` 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-mypy#54]
This occurs due to a bug in `mypy` itself: https://github.com/python/mypy/issues/10709

See this issue for a solution using mypy settings: https://github.com/python/mypy/issues/10709

Alternate workaround: Set `"mypy-type-checker.path": ["<path to mypy executable>"]`

**Comment by VoodaGod** [comment]
for anyone else getting confused by the discussion in https://github.com/python/mypy/issues/10709:
this issue is not fixed in mypy 1.4.1, looks like it will be included in 1.5 in middle of july
