### ISSUE TITLE
Feature request: Link to the error's documentation

### ISSUE THREAD

**Issue by Avasam** [microsoft/vscode-mypy#57]
I would like for the error info popup to also link to the appropriate error code documentation. For example `no-untyped-def` would link to https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-every-function-has-an-annotation-no-untyped-def . Similarly to how ESLint and Pylance do it: 
![image](https://github.com/microsoft/vscode-mypy/assets/1350584/d6099b65-af28-4409-9579-7d63f2efb201)
![image](https://github.com/microsoft/vscode-mypy/assets/1350584/dd9bd9ef-3118-4da2-91e0-8fa1340cc307)

I found that it is an extremely powerful tool for learning and help devs understand the errors. Especially newer developers who are less keen to go dig up documentation they don't even know if it exists.

**Comment by karthiknadig** [comment]
Thanks for the feature request! We are going to give the community time to provide upvotes on the opening comment to gauge general interest in this idea. If there's enough upvotes then we will consider this feature request in our future planning. If there's unfortunately not enough upvotes then we will close this issue.

**Comment by karthiknadig** [comment]
@Avasam We are open to take PR for this feature request. Here is a similar feature implemented for our pylint extension https://github.com/microsoft/vscode-pylint/pull/298 . This repo has the same structure as the pylint extension.

Here is our contributing guide for this repo to set it up: https://github.com/microsoft/vscode-mypy/wiki/Contributing-Guide
