### ISSUE TITLE
Rogue "missing return statement" errors

### ISSUE THREAD

**Issue by CallumAtCarter** [microsoft/vscode-mypy#62]
I am running the latest pre-release version of the extension with mypy 1.4.0 in the environment with `"mypy-type-checker.importStrategy": "fromEnvironment"`.

Quite often when opening a file, I am greeted with the following error on most of the lines:

> Missing return statement  [return]

Upon opening the extension logs, I can see that these errors appear to be coming from one or more type stubs:
```
2023-06-22 15:17:44.757 [info] [Trace - 3:17:44 PM] Received notification 'window/logMessage'.
2023-06-22 15:17:44.758 [info] file:///c%3A/Users/me/Documents/GitHub/project/some/file.py :
.venv\lib\site-packages\requests-stubs\api.pyi:10:1:28:18: error: Missing return statement  [return]
...
.venv\lib\site-packages\requests-stubs\api.pyi:137:1:154:18: error: Missing return statement  [return]
.venv\lib\site-packages\requests-stubs\sessions.pyi:315:1:315:29: error: Missing return statement  [return]
.venv\lib\site-packages\requests-stubs\utils.pyi:25:1:25:88: error: Missing return statement  [return]
...
.venv\lib\site-packages\requests-stubs\utils.pyi:68:5:68:44: error: Missing return statement  [return]
.venv\lib\site-packages\urllib3-stubs\filepost.pyi:14:1:14:33: error: Missing return statement  [return]
.venv\lib\site-packages\urllib3-stubs\filepost.pyi:15:1:15:75: error: Missing return statement  [return]
.venv\lib\site-packages\urllib3-stubs\filepost.pyi:17:1:17:106: error: Missing return statement  [return]
```

I don't see any of these errors when running `mypy .`

I tried adding `exclude = [".venv/"]` to my `pyproject.toml` file to no avail.

**Comment by karthiknadig** [comment]
@CallumAtCarter Does this report this when running on some file or just in general? Also, could you share some details what you have installed in your environment so I can repo this (maybe `python -m pip list`)?

**Comment by maunzCache** [comment]
Just wanted to confirm the behavior if --follow-imports is set to skip. Setting it to silent is working for me (and currently fine with my setup).
