### ISSUE TITLE
Can't install release version of 'ms-python.mypy-type-checker' extension because it has no release version

### ISSUE THREAD

**Issue by merc1er** [microsoft/vscode-mypy#78]
When trying to install the mypy extension, I am prompted with the following error:

![error](https://github.com/microsoft/vscode-mypy/assets/21960643/37bad470-e7d0-4d4c-80f0-58f8e147560a)

**Comment by karthiknadig** [comment]
This is expected, we will release a stable soon.

**Comment by karthiknadig** [comment]
Please use the dropdown right next to the `install` to install the pre-release version.
