### ISSUE TITLE
How is this extension related to python's extension setting `python.linting.mypyEnabled` ?

### ISSUE THREAD

**Issue by jacek-jablonski** [microsoft/vscode-mypy#79]
Hi,
Microsoft's Python extension already allows to lint code with MyPy. How is this extension different and how it relates to existing options in Python extension?

**Comment by CallumAtCarter** [comment]
@jacek-jablonski The latest VS Code release notes say this:

> There is now a [Mypy Type Checker](https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker) extension that provides type checking support for Python using [mypy](https://pypi.org/project/mypy/), available in preview as a pre-release version. This new extension offers errors and warnings on your entire codebase, instead of only the current file. It also uses [dmypy](https://mypy.readthedocs.io/en/stable/mypy_daemon.html) for faster type checking.

So it's for the entire codebase and it's faster because it uses `dmypy`.

**Comment by jacek-jablonski** [comment]
Thanks for explanation @CallumAtCarter
