### ISSUE TITLE
"Cannot find config file" in `mypy-type-checker.args`

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-mypy#80]
I'm migrating our mypy config from the Python extension to this one, but running into an issue when specifying a `--config-file`. Here's my config:
```
        "python.linting.mypyEnabled": false,
        "mypy-type-checker.path": [
            "/usr/bin/mypy"
        ],
        "mypy-type-checker.args": [
            "--exclude=install/",
            "--config-file=/depot/mypy.ini"
        ],
```

And here's the error I'm getting in the Output tab:
```
2023-07-07 12:34:57.132 [info] /usr/bin/mypy --no-color-output --no-error-summary --show-column-numbers --show-error-code --no-pretty --exclude=install/ --config-file=/depot/mypy.ini --show-error-end /depot/path/to/src.py
2023-07-07 12:34:57.133 [info] [Trace - 12:34:57 PM] Received notification 'window/logMessage'.
2023-07-07 12:34:57.133 [info] CWD Server: /depot
2023-07-07 12:34:57.242 [info] [Trace - 12:34:57 PM] Received notification 'window/logMessage'.
2023-07-07 12:34:57.242 [info] usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Cannot find config file '/depot/mypy.ini'
```

I've tried various flavors of the same flag but none of them seem to work.
* `["--config-file=/depot/mypy.ini"]` (what the docs recommend)
* `["--config-file=mypy.ini"]` (assuming it was doing relative paths from the CWD and not absolute?)
* `["--config-file", "/depot/mypy.ini"]` (space separated maybe?)
* `["--config-file", "mypy.ini"]`

**Comment by karthiknadig** [comment]
Is this working from a terminal? When you use `path` we literally just run this directly, can you try it from a terminal ans see if it works:
```
/usr/bin/mypy --no-color-output --no-error-summary --show-column-numbers --show-error-code --no-pretty --exclude=install/ --config-file=/depot/mypy.ini --show-error-end /depot/path/to/src.py
```

**Comment by dfarley1** [comment]
I'm an idiot, our mypy config moved recently and I forgot about it. I expected the CLI command was a directl copy/paste and should have tried it myself.
