### ISSUE TITLE
errors appearing in the wrong files

### ISSUE THREAD

**Issue by Avasam** [microsoft/vscode-mypy#82]
Error locations are all over the place, see:
![image](https://github.com/microsoft/vscode-mypy/assets/1350584/d7dec61b-3407-4c66-8879-12e5ee3d60ca)
![image](https://github.com/microsoft/vscode-mypy/assets/1350584/55b0bcee-884e-44ae-b63c-f7571931ff55)

I have restarted mypy server, reloaded window, closed and re-opened vscode, somehow it keeps getting worse.
For example, now it's 
![image](https://github.com/microsoft/vscode-mypy/assets/1350584/9ab4fbdd-abf0-4270-a2a3-617bd5e4a448)

Python 3.9.13
mypy 1.4.1 (compiled: yes)
ms-python.mypy-type-checker: v2023.1.11781017

**Comment by Avasam** [comment]
It might be due to removing `--follow-imports=skip` from my args in vscode settings.
Unfortunately, `--follow-imports=skip` means I'll get a lot of false positives in my IDE, and dmypy doesn't support `--follow-imports=silent` as seen by this message: `2023-07-10 03:18:47.197 [info] dmypy: follow-imports=silent not supported`

**Comment by karthiknadig** [comment]
This should be fixed via https://github.com/microsoft/vscode-mypy/pull/76

Will push a pre-release soon

Duplicate https://github.com/microsoft/vscode-mypy/issues/62

**Comment by karthiknadig** [comment]
Try with build `2023.1.11911749`
