### ISSUE TITLE
Should not use `--follow-imports=skip`

### ISSUE THREAD

**Issue by PeterJCLaw** [microsoft/vscode-mypy#89]
This extension improves on the default behaviour of the main Python extension's handling of `mypy` in terms of the options it passes, however it appears to silently pass `--follow-imports=skip`. This causes _all_ imports to be replaced by `Any`, in turn substantially limiting the usefulness of the type checking by causing both:
- spurious errors when used in combination with `warn_return_any` (possibly other cases too), and
- true errors to be missed, since any types imported (even from within the same project) are considered as `Any` and thus fully compatible with any other type

**Comment by levrik** [comment]
I think this has been changed in https://github.com/microsoft/vscode-mypy/pull/76 already. At least upgrading to the current pre-release has fixed this issue for me.

**Comment by PeterJCLaw** [comment]
Thanks, I hadn't spotted that. Unfortunately I don't think that that fixes the issue here -- which is that extension is setting a value at all that can therefore differ from what a project has configured.

If I recall correctly, `mypy` treats CLI options at a higher priority than those found in any configuration files, meaning that the extension passing any value here will always override what the user has configured for their project. While `--follow-imports=normal` (as set by #76) is much more likely to match what projects use, it is still an explicit override which may differ from what users see when running on the command line/in CI/etc.

**Comment by karthiknadig** [comment]
@PeterJCLaw We don't really have a reason for this default other than it was what was in defaults for the python extension. We can remove it. We are open to a PR removing it.
