### ISSUE TITLE
cannot find module or stub on all nonstandard packages when using pipenv

### ISSUE THREAD

**Issue by skewballfox** [microsoft/vscode-mypy#91]
This may be user error, or may be more generalized than pipenv. I recently switched to using the mypy extension from using mypy within pylance. For every import for this project that isn't part of the standard library, mypy is producing a variation of the following error: 
```
Cannot find implementation or library stub for module named "numpy.typing"
```
the python interpreter from within the virtual environment is active within vscode, and I'm getting lints like normal from pylance

**Comment by karthiknadig** [comment]
This is not an extension issue, it looks like you need to enable the plugin to use it:
https://numpy.org/devdocs/release/1.22.0-notes.html#assign-the-platform-specific-c-intp-precision-via-a-mypy-plugin

**Comment by karthiknadig** [comment]
If you do have that setting in your config file and it is not picking it up, please try the pre-release version of the extension. Also, you can try adding `"mypy-type-checker.args" = ["--config-file=<file>"]` to your settings to see if it helps. Please let us know if this does not work, we can re-open the issue to investigate further.
